name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Node env
      uses: actions/setup-node

    - name: Rust env
      run: curl https://sh.rustup.rs -sSf | sh

    - name: Rust build
      run: cargo build

    - name: Npm build
      run: npm install && npm run build
    
